package database;

// Generated 12-mar-2013 15:01:36 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BasicData generated by hbm2java
 */
@Entity
@Table(name = "basic_data", catalog = "ascensor_nardi")
public class BasicData implements java.io.Serializable {

	private Integer idBasic;
	private BasicData basicData;
	private String dataBaseName;
	private String name;
	private String field;
	private boolean editable;
	private int priority;
	private char status;
	private Set<Budget> budgetsForVoltageLighting = new HashSet<Budget>(0);
	private Set<Budget> budgetsForFrequency = new HashSet<Budget>(0);
	private Set<Budget> budgetsForHourMachine = new HashSet<Budget>(0);
	private Set<Budget> budgetsForMirror = new HashSet<Budget>(0);
	private Set<Budget> budgetsForRailing = new HashSet<Budget>(0);
	private Set<Budget> budgetsForButtonType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForRoofType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForHeight = new HashSet<Budget>(0);
	private Set<Budget> budgetsForHallButtonType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForCabinDesign = new HashSet<Budget>(0);
	private Set<Budget> budgetsForManeuverType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForHallButton = new HashSet<Budget>(0);
	private Set<Budget> budgetsForFreeAdmission = new HashSet<Budget>(0);
	private Set<BasicData> basicDatas = new HashSet<BasicData>(0);
	private Set<Budget> budgetsForSpeed = new HashSet<Budget>(0);
	private Set<Budget> budgetsForFloorType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForDoorSystem = new HashSet<Budget>(0);
	private Set<Budget> budgetsForBuildingType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForDoorframeType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForElevatorType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForControlType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForBoothButton = new HashSet<Budget>(0);
	private Set<Budget> budgetsForElevatorCapacitance = new HashSet<Budget>(0);
	private Set<Budget> budgetsForDoorFrameHammered = new HashSet<Budget>(0);
	private Set<Budget> budgetsForBoothDisplay = new HashSet<Budget>(0);
	private Set<Budget> budgetsForMachineType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForFloorDisplay = new HashSet<Budget>(0);
	private Set<Budget> budgetsForAccess = new HashSet<Budget>(0);
	private Set<Budget> budgetsForElectricityType = new HashSet<Budget>(0);
	private Set<Budget> budgetsForFan = new HashSet<Budget>(0);
	private Set<Budget> budgetsForDoorType = new HashSet<Budget>(0);

	public BasicData() {
	}

	public BasicData(String dataBaseName, String name, String field,
			boolean editable, int priority, char status) {
		this.dataBaseName = dataBaseName;
		this.name = name;
		this.field = field;
		this.editable = editable;
		this.priority = priority;
		this.status = status;
	}

	public BasicData(BasicData basicData, String dataBaseName, String name,
			String field, boolean editable, int priority, char status,
			Set<Budget> budgetsForVoltageLighting,
			Set<Budget> budgetsForFrequency, Set<Budget> budgetsForHourMachine,
			Set<Budget> budgetsForMirror, Set<Budget> budgetsForRailing,
			Set<Budget> budgetsForButtonType, Set<Budget> budgetsForRoofType,
			Set<Budget> budgetsForHeight, Set<Budget> budgetsForHallButtonType,
			Set<Budget> budgetsForCabinDesign,
			Set<Budget> budgetsForManeuverType,
			Set<Budget> budgetsForHallButton,
			Set<Budget> budgetsForFreeAdmission, Set<BasicData> basicDatas,
			Set<Budget> budgetsForSpeed, Set<Budget> budgetsForFloorType,
			Set<Budget> budgetsForDoorSystem,
			Set<Budget> budgetsForBuildingType,
			Set<Budget> budgetsForDoorframeType,
			Set<Budget> budgetsForElevatorType,
			Set<Budget> budgetsForControlType,
			Set<Budget> budgetsForBoothButton,
			Set<Budget> budgetsForElevatorCapacitance,
			Set<Budget> budgetsForDoorFrameHammered,
			Set<Budget> budgetsForBoothDisplay,
			Set<Budget> budgetsForMachineType,
			Set<Budget> budgetsForFloorDisplay, Set<Budget> budgetsForAccess,
			Set<Budget> budgetsForElectricityType, Set<Budget> budgetsForFan,
			Set<Budget> budgetsForDoorType) {
		this.basicData = basicData;
		this.dataBaseName = dataBaseName;
		this.name = name;
		this.field = field;
		this.editable = editable;
		this.priority = priority;
		this.status = status;
		this.budgetsForVoltageLighting = budgetsForVoltageLighting;
		this.budgetsForFrequency = budgetsForFrequency;
		this.budgetsForHourMachine = budgetsForHourMachine;
		this.budgetsForMirror = budgetsForMirror;
		this.budgetsForRailing = budgetsForRailing;
		this.budgetsForButtonType = budgetsForButtonType;
		this.budgetsForRoofType = budgetsForRoofType;
		this.budgetsForHeight = budgetsForHeight;
		this.budgetsForHallButtonType = budgetsForHallButtonType;
		this.budgetsForCabinDesign = budgetsForCabinDesign;
		this.budgetsForManeuverType = budgetsForManeuverType;
		this.budgetsForHallButton = budgetsForHallButton;
		this.budgetsForFreeAdmission = budgetsForFreeAdmission;
		this.basicDatas = basicDatas;
		this.budgetsForSpeed = budgetsForSpeed;
		this.budgetsForFloorType = budgetsForFloorType;
		this.budgetsForDoorSystem = budgetsForDoorSystem;
		this.budgetsForBuildingType = budgetsForBuildingType;
		this.budgetsForDoorframeType = budgetsForDoorframeType;
		this.budgetsForElevatorType = budgetsForElevatorType;
		this.budgetsForControlType = budgetsForControlType;
		this.budgetsForBoothButton = budgetsForBoothButton;
		this.budgetsForElevatorCapacitance = budgetsForElevatorCapacitance;
		this.budgetsForDoorFrameHammered = budgetsForDoorFrameHammered;
		this.budgetsForBoothDisplay = budgetsForBoothDisplay;
		this.budgetsForMachineType = budgetsForMachineType;
		this.budgetsForFloorDisplay = budgetsForFloorDisplay;
		this.budgetsForAccess = budgetsForAccess;
		this.budgetsForElectricityType = budgetsForElectricityType;
		this.budgetsForFan = budgetsForFan;
		this.budgetsForDoorType = budgetsForDoorType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idBasic", unique = true, nullable = false)
	public Integer getIdBasic() {
		return this.idBasic;
	}

	public void setIdBasic(Integer idBasic) {
		this.idBasic = idBasic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Parent_idBasic")
	public BasicData getBasicData() {
		return this.basicData;
	}

	public void setBasicData(BasicData basicData) {
		this.basicData = basicData;
	}

	@Column(name = "dataBaseName", nullable = false, length = 50)
	public String getDataBaseName() {
		return this.dataBaseName;
	}

	public void setDataBaseName(String dataBaseName) {
		this.dataBaseName = dataBaseName;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "field", nullable = false, length = 300)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "editable", nullable = false)
	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByVoltageLighting")
	public Set<Budget> getBudgetsForVoltageLighting() {
		return this.budgetsForVoltageLighting;
	}

	public void setBudgetsForVoltageLighting(
			Set<Budget> budgetsForVoltageLighting) {
		this.budgetsForVoltageLighting = budgetsForVoltageLighting;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByFrequency")
	public Set<Budget> getBudgetsForFrequency() {
		return this.budgetsForFrequency;
	}

	public void setBudgetsForFrequency(Set<Budget> budgetsForFrequency) {
		this.budgetsForFrequency = budgetsForFrequency;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByHourMachine")
	public Set<Budget> getBudgetsForHourMachine() {
		return this.budgetsForHourMachine;
	}

	public void setBudgetsForHourMachine(Set<Budget> budgetsForHourMachine) {
		this.budgetsForHourMachine = budgetsForHourMachine;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByMirror")
	public Set<Budget> getBudgetsForMirror() {
		return this.budgetsForMirror;
	}

	public void setBudgetsForMirror(Set<Budget> budgetsForMirror) {
		this.budgetsForMirror = budgetsForMirror;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByRailing")
	public Set<Budget> getBudgetsForRailing() {
		return this.budgetsForRailing;
	}

	public void setBudgetsForRailing(Set<Budget> budgetsForRailing) {
		this.budgetsForRailing = budgetsForRailing;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByButtonType")
	public Set<Budget> getBudgetsForButtonType() {
		return this.budgetsForButtonType;
	}

	public void setBudgetsForButtonType(Set<Budget> budgetsForButtonType) {
		this.budgetsForButtonType = budgetsForButtonType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByRoofType")
	public Set<Budget> getBudgetsForRoofType() {
		return this.budgetsForRoofType;
	}

	public void setBudgetsForRoofType(Set<Budget> budgetsForRoofType) {
		this.budgetsForRoofType = budgetsForRoofType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByHeight")
	public Set<Budget> getBudgetsForHeight() {
		return this.budgetsForHeight;
	}

	public void setBudgetsForHeight(Set<Budget> budgetsForHeight) {
		this.budgetsForHeight = budgetsForHeight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByHallButtonType")
	public Set<Budget> getBudgetsForHallButtonType() {
		return this.budgetsForHallButtonType;
	}

	public void setBudgetsForHallButtonType(Set<Budget> budgetsForHallButtonType) {
		this.budgetsForHallButtonType = budgetsForHallButtonType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByCabinDesign")
	public Set<Budget> getBudgetsForCabinDesign() {
		return this.budgetsForCabinDesign;
	}

	public void setBudgetsForCabinDesign(Set<Budget> budgetsForCabinDesign) {
		this.budgetsForCabinDesign = budgetsForCabinDesign;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByManeuverType")
	public Set<Budget> getBudgetsForManeuverType() {
		return this.budgetsForManeuverType;
	}

	public void setBudgetsForManeuverType(Set<Budget> budgetsForManeuverType) {
		this.budgetsForManeuverType = budgetsForManeuverType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByHallButton")
	public Set<Budget> getBudgetsForHallButton() {
		return this.budgetsForHallButton;
	}

	public void setBudgetsForHallButton(Set<Budget> budgetsForHallButton) {
		this.budgetsForHallButton = budgetsForHallButton;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByFreeAdmission")
	public Set<Budget> getBudgetsForFreeAdmission() {
		return this.budgetsForFreeAdmission;
	}

	public void setBudgetsForFreeAdmission(Set<Budget> budgetsForFreeAdmission) {
		this.budgetsForFreeAdmission = budgetsForFreeAdmission;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicData")
	public Set<BasicData> getBasicDatas() {
		return this.basicDatas;
	}

	public void setBasicDatas(Set<BasicData> basicDatas) {
		this.basicDatas = basicDatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataBySpeed")
	public Set<Budget> getBudgetsForSpeed() {
		return this.budgetsForSpeed;
	}

	public void setBudgetsForSpeed(Set<Budget> budgetsForSpeed) {
		this.budgetsForSpeed = budgetsForSpeed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByFloorType")
	public Set<Budget> getBudgetsForFloorType() {
		return this.budgetsForFloorType;
	}

	public void setBudgetsForFloorType(Set<Budget> budgetsForFloorType) {
		this.budgetsForFloorType = budgetsForFloorType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByDoorSystem")
	public Set<Budget> getBudgetsForDoorSystem() {
		return this.budgetsForDoorSystem;
	}

	public void setBudgetsForDoorSystem(Set<Budget> budgetsForDoorSystem) {
		this.budgetsForDoorSystem = budgetsForDoorSystem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByBuildingType")
	public Set<Budget> getBudgetsForBuildingType() {
		return this.budgetsForBuildingType;
	}

	public void setBudgetsForBuildingType(Set<Budget> budgetsForBuildingType) {
		this.budgetsForBuildingType = budgetsForBuildingType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByDoorframeType")
	public Set<Budget> getBudgetsForDoorframeType() {
		return this.budgetsForDoorframeType;
	}

	public void setBudgetsForDoorframeType(Set<Budget> budgetsForDoorframeType) {
		this.budgetsForDoorframeType = budgetsForDoorframeType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByElevatorType")
	public Set<Budget> getBudgetsForElevatorType() {
		return this.budgetsForElevatorType;
	}

	public void setBudgetsForElevatorType(Set<Budget> budgetsForElevatorType) {
		this.budgetsForElevatorType = budgetsForElevatorType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByControlType")
	public Set<Budget> getBudgetsForControlType() {
		return this.budgetsForControlType;
	}

	public void setBudgetsForControlType(Set<Budget> budgetsForControlType) {
		this.budgetsForControlType = budgetsForControlType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByBoothButton")
	public Set<Budget> getBudgetsForBoothButton() {
		return this.budgetsForBoothButton;
	}

	public void setBudgetsForBoothButton(Set<Budget> budgetsForBoothButton) {
		this.budgetsForBoothButton = budgetsForBoothButton;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByElevatorCapacitance")
	public Set<Budget> getBudgetsForElevatorCapacitance() {
		return this.budgetsForElevatorCapacitance;
	}

	public void setBudgetsForElevatorCapacitance(
			Set<Budget> budgetsForElevatorCapacitance) {
		this.budgetsForElevatorCapacitance = budgetsForElevatorCapacitance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByDoorFrameHammered")
	public Set<Budget> getBudgetsForDoorFrameHammered() {
		return this.budgetsForDoorFrameHammered;
	}

	public void setBudgetsForDoorFrameHammered(
			Set<Budget> budgetsForDoorFrameHammered) {
		this.budgetsForDoorFrameHammered = budgetsForDoorFrameHammered;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByBoothDisplay")
	public Set<Budget> getBudgetsForBoothDisplay() {
		return this.budgetsForBoothDisplay;
	}

	public void setBudgetsForBoothDisplay(Set<Budget> budgetsForBoothDisplay) {
		this.budgetsForBoothDisplay = budgetsForBoothDisplay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByMachineType")
	public Set<Budget> getBudgetsForMachineType() {
		return this.budgetsForMachineType;
	}

	public void setBudgetsForMachineType(Set<Budget> budgetsForMachineType) {
		this.budgetsForMachineType = budgetsForMachineType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByFloorDisplay")
	public Set<Budget> getBudgetsForFloorDisplay() {
		return this.budgetsForFloorDisplay;
	}

	public void setBudgetsForFloorDisplay(Set<Budget> budgetsForFloorDisplay) {
		this.budgetsForFloorDisplay = budgetsForFloorDisplay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByAccess")
	public Set<Budget> getBudgetsForAccess() {
		return this.budgetsForAccess;
	}

	public void setBudgetsForAccess(Set<Budget> budgetsForAccess) {
		this.budgetsForAccess = budgetsForAccess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByElectricityType")
	public Set<Budget> getBudgetsForElectricityType() {
		return this.budgetsForElectricityType;
	}

	public void setBudgetsForElectricityType(
			Set<Budget> budgetsForElectricityType) {
		this.budgetsForElectricityType = budgetsForElectricityType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByFan")
	public Set<Budget> getBudgetsForFan() {
		return this.budgetsForFan;
	}

	public void setBudgetsForFan(Set<Budget> budgetsForFan) {
		this.budgetsForFan = budgetsForFan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicDataByDoorType")
	public Set<Budget> getBudgetsForDoorType() {
		return this.budgetsForDoorType;
	}

	public void setBudgetsForDoorType(Set<Budget> budgetsForDoorType) {
		this.budgetsForDoorType = budgetsForDoorType;
	}

}
