package database;

// Generated 28/11/2012 02:48:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name = "budget", schema = "public")
public class Budget implements java.io.Serializable {

	private int idbudget;
	private Basicdata basicdataByButtontype;
	private Basicdata basicdataByMachinetype;
	private Basicdata basicdataByBoothdisplay;
	private Basicdata basicdataByManeuvertype;
	private Basicdata basicdataByFrequency;
	private Basicdata basicdataByMirror;
	private Basicdata basicdataByFloordisplay;
	private Basicdata basicdataByVoltagelighting;
	private Basicdata basicdataByElectricitytype;
	private Basicdata basicdataByRailing;
	private Basicdata basicdataByDoortype;
	private Basicdata basicdataByFloortype;
	private Basicdata basicdataByBuildingtype;
	private Basicdata basicdataByDesign1357;
	private Basicdata basicdataByElevatorcapacitance;
	private Basicdata basicdataByRooftype;
	private Basicdata basicdataByFan;
	private Basicdata basicdataByHeight;
	private Basicdata basicdataBySpeed;
	private Basicdata basicdataByEmbarque;
	private Basicdata basicdataByFreeadmission;
	private Basicdata basicdataByControltype;
	private Basicdata basicdataByDesignp26;
	private Basicdata basicdataByElevatortype;
	private Basicdata basicdataByBoothbutton;
	private Basicdata basicdataByDoorsystem;
	private Basicdata basicdataByHourmachine;
	private Basicdata basicdataByDoorframetype;
	private int number;
	private Date date;
	private String partnername;
	private String construction;
	private String constructionnumber;
	private String seller;
	private String constructionaddress;
	private String constructioncity;
	private String contactphone;
	private String email;
	private String contactname;
	private Boolean planep;
	private Boolean planec;
	private boolean type;
	private Integer elevatorquantity;
	private Integer motorquantity;
	private String motortraction;
	private Integer stopnumber;
	private Integer tour;
	private Integer ontour;
	private Integer widthhole;
	private Integer fossa;
	private Integer bottomhole;
	private Boolean designspecial;
	private String designspecialcomment;
	private Integer doorofnumber;
	private String hallbutton;
	private Boolean lightcurtain;
	private Boolean loadlimiter;
	private Boolean speechsynthesizer;
	private Boolean gomsystem;
	private Boolean intercom;
	private Boolean phone;
	private Boolean accesssytem;
	private Boolean firefighterkeychain;
	private String comment;
	private String displayplacefloor;
	private Boolean stopsequencecontinuous;
	private String stopsequencecontinuousq;
	private Boolean stopsequenceeven;
	private String stopsequenceevenq;
	private Boolean stopsequenceodd;
	private String stopsequenceoddq;
	private Boolean doorframegray;
	private String doorframegraydescrip;
	private Boolean doorframebrown;
	private String doorframebrowndescrip;
	private Boolean doorframestainless;
	private String doorframestainlessdescrip;
	private Integer sistelwdisplaypb;
	private Integer sistelwdisplayfloor;
	private Integer sistelwarrowpb;
	private Integer sistelwarrowfloor;
	private Integer braile37pb;
	private Integer braile37floor;
	private Integer antivandalismpb;
	private Integer antivandalismfloor;
	private char status;

	public Budget() {
	}

	public Budget(int idbudget, int number, Date date, String partnername,
			String construction, String constructionnumber, String seller,
			String constructionaddress, String constructioncity,
			String contactphone, String email, String contactname,
			boolean type, Integer braile37pb, Integer antivandalismfloor, char status) {
		this.idbudget = idbudget;
		this.number = number;
		this.date = date;
		this.partnername = partnername;
		this.construction = construction;
		this.constructionnumber = constructionnumber;
		this.seller = seller;
		this.constructionaddress = constructionaddress;
		this.constructioncity = constructioncity;
		this.contactphone = contactphone;
		this.email = email;
		this.contactname = contactname;
		this.type = type;
		this.braile37pb = braile37pb;
		this.antivandalismfloor = antivandalismfloor;
		this.status = status;
	}

	public Budget(int idbudget, Basicdata basicdataByButtontype,
			Basicdata basicdataByMachinetype,
			Basicdata basicdataByBoothdisplay,
			Basicdata basicdataByManeuvertype, Basicdata basicdataByFrequency,
			Basicdata basicdataByMirror, Basicdata basicdataByFloordisplay,
			Basicdata basicdataByVoltagelighting,
			Basicdata basicdataByElectricitytype, Basicdata basicdataByRailing,
			Basicdata basicdataByDoortype, Basicdata basicdataByFloortype,
			Basicdata basicdataByBuildingtype, Basicdata basicdataByDesign1357,
			Basicdata basicdataByElevatorcapacitance,
			Basicdata basicdataByRooftype, Basicdata basicdataByFan,
			Basicdata basicdataByHeight, Basicdata basicdataBySpeed,
			Basicdata basicdataByEmbarque, Basicdata basicdataByFreeadmission,
			Basicdata basicdataByControltype, Basicdata basicdataByDesignp26,
			Basicdata basicdataByElevatortype,
			Basicdata basicdataByBoothbutton, Basicdata basicdataByDoorsystem,
			Basicdata basicdataByHourmachine,
			Basicdata basicdataByDoorframetype, int number, Date date,
			String partnername, String construction, String constructionnumber,
			String seller, String constructionaddress, String constructioncity,
			String contactphone, String email, String contactname,
			Boolean planep, Boolean planec, boolean type,
			Integer elevatorquantity, Integer motorquantity,
			String motortraction, Integer stopnumber, Integer tour,
			Integer ontour, Integer widthhole, Integer fossa,
			Integer bottomhole, Boolean designspecial,
			String designspecialcomment, Integer doorofnumber,
			String hallbutton, Boolean lightcurtain, Boolean loadlimiter,
			Boolean speechsynthesizer, Boolean gomsystem, Boolean intercom,
			Boolean phone, Boolean accesssytem, Boolean firefighterkeychain,
			String comment, String displayplacefloor,
			Boolean stopsequencecontinuous, String stopsequencecontinuousq,
			Boolean stopsequenceeven, String stopsequenceevenq,
			Boolean stopsequenceodd, String stopsequenceoddq,
			Boolean doorframegray, String doorframegraydescrip,
			Boolean doorframebrown, String doorframebrowndescrip,
			Boolean doorframestainless, String doorframestainlessdescrip,
			Integer sistelwdisplaypb, Integer sistelwdisplayfloor,
			Integer sistelwarrowpb, Integer sistelwarrowfloor, Integer braile37pb,
			Integer braile37floor, Integer antivandalismpb,
			Integer antivandalismfloor, char status) {
		this.idbudget = idbudget;
		this.basicdataByButtontype = basicdataByButtontype;
		this.basicdataByMachinetype = basicdataByMachinetype;
		this.basicdataByBoothdisplay = basicdataByBoothdisplay;
		this.basicdataByManeuvertype = basicdataByManeuvertype;
		this.basicdataByFrequency = basicdataByFrequency;
		this.basicdataByMirror = basicdataByMirror;
		this.basicdataByFloordisplay = basicdataByFloordisplay;
		this.basicdataByVoltagelighting = basicdataByVoltagelighting;
		this.basicdataByElectricitytype = basicdataByElectricitytype;
		this.basicdataByRailing = basicdataByRailing;
		this.basicdataByDoortype = basicdataByDoortype;
		this.basicdataByFloortype = basicdataByFloortype;
		this.basicdataByBuildingtype = basicdataByBuildingtype;
		this.basicdataByDesign1357 = basicdataByDesign1357;
		this.basicdataByElevatorcapacitance = basicdataByElevatorcapacitance;
		this.basicdataByRooftype = basicdataByRooftype;
		this.basicdataByFan = basicdataByFan;
		this.basicdataByHeight = basicdataByHeight;
		this.basicdataBySpeed = basicdataBySpeed;
		this.basicdataByEmbarque = basicdataByEmbarque;
		this.basicdataByFreeadmission = basicdataByFreeadmission;
		this.basicdataByControltype = basicdataByControltype;
		this.basicdataByDesignp26 = basicdataByDesignp26;
		this.basicdataByElevatortype = basicdataByElevatortype;
		this.basicdataByBoothbutton = basicdataByBoothbutton;
		this.basicdataByDoorsystem = basicdataByDoorsystem;
		this.basicdataByHourmachine = basicdataByHourmachine;
		this.basicdataByDoorframetype = basicdataByDoorframetype;
		this.number = number;
		this.date = date;
		this.partnername = partnername;
		this.construction = construction;
		this.constructionnumber = constructionnumber;
		this.seller = seller;
		this.constructionaddress = constructionaddress;
		this.constructioncity = constructioncity;
		this.contactphone = contactphone;
		this.email = email;
		this.contactname = contactname;
		this.planep = planep;
		this.planec = planec;
		this.type = type;
		this.elevatorquantity = elevatorquantity;
		this.motorquantity = motorquantity;
		this.motortraction = motortraction;
		this.stopnumber = stopnumber;
		this.tour = tour;
		this.ontour = ontour;
		this.widthhole = widthhole;
		this.fossa = fossa;
		this.bottomhole = bottomhole;
		this.designspecial = designspecial;
		this.designspecialcomment = designspecialcomment;
		this.doorofnumber = doorofnumber;
		this.hallbutton = hallbutton;
		this.lightcurtain = lightcurtain;
		this.loadlimiter = loadlimiter;
		this.speechsynthesizer = speechsynthesizer;
		this.gomsystem = gomsystem;
		this.intercom = intercom;
		this.phone = phone;
		this.accesssytem = accesssytem;
		this.firefighterkeychain = firefighterkeychain;
		this.comment = comment;
		this.displayplacefloor = displayplacefloor;
		this.stopsequencecontinuous = stopsequencecontinuous;
		this.stopsequencecontinuousq = stopsequencecontinuousq;
		this.stopsequenceeven = stopsequenceeven;
		this.stopsequenceevenq = stopsequenceevenq;
		this.stopsequenceodd = stopsequenceodd;
		this.stopsequenceoddq = stopsequenceoddq;
		this.doorframegray = doorframegray;
		this.doorframegraydescrip = doorframegraydescrip;
		this.doorframebrown = doorframebrown;
		this.doorframebrowndescrip = doorframebrowndescrip;
		this.doorframestainless = doorframestainless;
		this.doorframestainlessdescrip = doorframestainlessdescrip;
		this.sistelwdisplaypb = sistelwdisplaypb;
		this.sistelwdisplayfloor = sistelwdisplayfloor;
		this.sistelwarrowpb = sistelwarrowpb;
		this.sistelwarrowfloor = sistelwarrowfloor;
		this.braile37pb = braile37pb;
		this.braile37floor = braile37floor;
		this.antivandalismpb = antivandalismpb;
		this.antivandalismfloor = antivandalismfloor;
		this.status = status;
	}

	/**
	 * <b>@GeneratedValue</b> es la forma de darle a la base de datos la
	 * responsabilidad de generar los id(Cuando son autoincrementables
	 * y son clave primaria).
	 * <b>@SequenceGenerator</b> es la secuencia generada en la base
	 * de datos (En este caso postgres) que controla ese autoincremento. 
	 * @return
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator="budget_seq")
	@SequenceGenerator(name="budget_seq", sequenceName="budget_idbudget_seq")
	@Column(name = "idbudget", unique = true, nullable = false)
	public int getIdbudget() {
		return this.idbudget;
	}

	public void setIdbudget(int idbudget) {
		this.idbudget = idbudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buttontype")
	public Basicdata getBasicdataByButtontype() {
		return this.basicdataByButtontype;
	}

	public void setBasicdataByButtontype(Basicdata basicdataByButtontype) {
		this.basicdataByButtontype = basicdataByButtontype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "machinetype")
	public Basicdata getBasicdataByMachinetype() {
		return this.basicdataByMachinetype;
	}

	public void setBasicdataByMachinetype(Basicdata basicdataByMachinetype) {
		this.basicdataByMachinetype = basicdataByMachinetype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boothdisplay")
	public Basicdata getBasicdataByBoothdisplay() {
		return this.basicdataByBoothdisplay;
	}

	public void setBasicdataByBoothdisplay(Basicdata basicdataByBoothdisplay) {
		this.basicdataByBoothdisplay = basicdataByBoothdisplay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maneuvertype")
	public Basicdata getBasicdataByManeuvertype() {
		return this.basicdataByManeuvertype;
	}

	public void setBasicdataByManeuvertype(Basicdata basicdataByManeuvertype) {
		this.basicdataByManeuvertype = basicdataByManeuvertype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frequency")
	public Basicdata getBasicdataByFrequency() {
		return this.basicdataByFrequency;
	}

	public void setBasicdataByFrequency(Basicdata basicdataByFrequency) {
		this.basicdataByFrequency = basicdataByFrequency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mirror")
	public Basicdata getBasicdataByMirror() {
		return this.basicdataByMirror;
	}

	public void setBasicdataByMirror(Basicdata basicdataByMirror) {
		this.basicdataByMirror = basicdataByMirror;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "floordisplay")
	public Basicdata getBasicdataByFloordisplay() {
		return this.basicdataByFloordisplay;
	}

	public void setBasicdataByFloordisplay(Basicdata basicdataByFloordisplay) {
		this.basicdataByFloordisplay = basicdataByFloordisplay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voltagelighting")
	public Basicdata getBasicdataByVoltagelighting() {
		return this.basicdataByVoltagelighting;
	}

	public void setBasicdataByVoltagelighting(
			Basicdata basicdataByVoltagelighting) {
		this.basicdataByVoltagelighting = basicdataByVoltagelighting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "electricitytype")
	public Basicdata getBasicdataByElectricitytype() {
		return this.basicdataByElectricitytype;
	}

	public void setBasicdataByElectricitytype(
			Basicdata basicdataByElectricitytype) {
		this.basicdataByElectricitytype = basicdataByElectricitytype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "railing")
	public Basicdata getBasicdataByRailing() {
		return this.basicdataByRailing;
	}

	public void setBasicdataByRailing(Basicdata basicdataByRailing) {
		this.basicdataByRailing = basicdataByRailing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doortype")
	public Basicdata getBasicdataByDoortype() {
		return this.basicdataByDoortype;
	}

	public void setBasicdataByDoortype(Basicdata basicdataByDoortype) {
		this.basicdataByDoortype = basicdataByDoortype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "floortype")
	public Basicdata getBasicdataByFloortype() {
		return this.basicdataByFloortype;
	}

	public void setBasicdataByFloortype(Basicdata basicdataByFloortype) {
		this.basicdataByFloortype = basicdataByFloortype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buildingtype")
	public Basicdata getBasicdataByBuildingtype() {
		return this.basicdataByBuildingtype;
	}

	public void setBasicdataByBuildingtype(Basicdata basicdataByBuildingtype) {
		this.basicdataByBuildingtype = basicdataByBuildingtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "design1357")
	public Basicdata getBasicdataByDesign1357() {
		return this.basicdataByDesign1357;
	}

	public void setBasicdataByDesign1357(Basicdata basicdataByDesign1357) {
		this.basicdataByDesign1357 = basicdataByDesign1357;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elevatorcapacitance")
	public Basicdata getBasicdataByElevatorcapacitance() {
		return this.basicdataByElevatorcapacitance;
	}

	public void setBasicdataByElevatorcapacitance(
			Basicdata basicdataByElevatorcapacitance) {
		this.basicdataByElevatorcapacitance = basicdataByElevatorcapacitance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rooftype")
	public Basicdata getBasicdataByRooftype() {
		return this.basicdataByRooftype;
	}

	public void setBasicdataByRooftype(Basicdata basicdataByRooftype) {
		this.basicdataByRooftype = basicdataByRooftype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fan")
	public Basicdata getBasicdataByFan() {
		return this.basicdataByFan;
	}

	public void setBasicdataByFan(Basicdata basicdataByFan) {
		this.basicdataByFan = basicdataByFan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "height")
	public Basicdata getBasicdataByHeight() {
		return this.basicdataByHeight;
	}

	public void setBasicdataByHeight(Basicdata basicdataByHeight) {
		this.basicdataByHeight = basicdataByHeight;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "speed")
	public Basicdata getBasicdataBySpeed() {
		return this.basicdataBySpeed;
	}

	public void setBasicdataBySpeed(Basicdata basicdataBySpeed) {
		this.basicdataBySpeed = basicdataBySpeed;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "embarque")
	public Basicdata getBasicdataByEmbarque() {
		return this.basicdataByEmbarque;
	}

	public void setBasicdataByEmbarque(Basicdata basicdataByEmbarque) {
		this.basicdataByEmbarque = basicdataByEmbarque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "freeadmission")
	public Basicdata getBasicdataByFreeadmission() {
		return this.basicdataByFreeadmission;
	}

	public void setBasicdataByFreeadmission(Basicdata basicdataByFreeadmission) {
		this.basicdataByFreeadmission = basicdataByFreeadmission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "controltype")
	public Basicdata getBasicdataByControltype() {
		return this.basicdataByControltype;
	}

	public void setBasicdataByControltype(Basicdata basicdataByControltype) {
		this.basicdataByControltype = basicdataByControltype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "designp26")
	public Basicdata getBasicdataByDesignp26() {
		return this.basicdataByDesignp26;
	}

	public void setBasicdataByDesignp26(Basicdata basicdataByDesignp26) {
		this.basicdataByDesignp26 = basicdataByDesignp26;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elevatortype")
	public Basicdata getBasicdataByElevatortype() {
		return this.basicdataByElevatortype;
	}

	public void setBasicdataByElevatortype(Basicdata basicdataByElevatortype) {
		this.basicdataByElevatortype = basicdataByElevatortype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boothbutton")
	public Basicdata getBasicdataByBoothbutton() {
		return this.basicdataByBoothbutton;
	}

	public void setBasicdataByBoothbutton(Basicdata basicdataByBoothbutton) {
		this.basicdataByBoothbutton = basicdataByBoothbutton;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doorsystem")
	public Basicdata getBasicdataByDoorsystem() {
		return this.basicdataByDoorsystem;
	}

	public void setBasicdataByDoorsystem(Basicdata basicdataByDoorsystem) {
		this.basicdataByDoorsystem = basicdataByDoorsystem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hourmachine")
	public Basicdata getBasicdataByHourmachine() {
		return this.basicdataByHourmachine;
	}

	public void setBasicdataByHourmachine(Basicdata basicdataByHourmachine) {
		this.basicdataByHourmachine = basicdataByHourmachine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doorframetype")
	public Basicdata getBasicdataByDoorframetype() {
		return this.basicdataByDoorframetype;
	}

	public void setBasicdataByDoorframetype(Basicdata basicdataByDoorframetype) {
		this.basicdataByDoorframetype = basicdataByDoorframetype;
	}

	/**
	 * <b>@Generated</B> con generationTime.ALWAYS es la forma de 
	 * autoincrementar el campo cuando el campo no es primario,
	 * y la base de datos le ha asignado una secuencia incrementable.
	 * @return
	 */
	@Generated(GenerationTime.ALWAYS)
	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "partnername", nullable = false, length = 100)
	public String getPartnername() {
		return this.partnername;
	}

	public void setPartnername(String partnername) {
		this.partnername = partnername;
	}

	@Column(name = "construction", nullable = false, length = 100)
	public String getConstruction() {
		return this.construction;
	}

	public void setConstruction(String construction) {
		this.construction = construction;
	}

	@Column(name = "constructionnumber", nullable = false, length = 15)
	public String getConstructionnumber() {
		return this.constructionnumber;
	}

	public void setConstructionnumber(String constructionnumber) {
		this.constructionnumber = constructionnumber;
	}

	@Column(name = "seller", nullable = false, length = 100)
	public String getSeller() {
		return this.seller;
	}

	public void setSeller(String seller) {
		this.seller = seller;
	}

	@Column(name = "constructionaddress", nullable = false, length = 200)
	public String getConstructionaddress() {
		return this.constructionaddress;
	}

	public void setConstructionaddress(String constructionaddress) {
		this.constructionaddress = constructionaddress;
	}

	@Column(name = "constructioncity", nullable = false, length = 100)
	public String getConstructioncity() {
		return this.constructioncity;
	}

	public void setConstructioncity(String constructioncity) {
		this.constructioncity = constructioncity;
	}

	@Column(name = "contactphone", nullable = false, length = 15)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contactname", nullable = false, length = 100)
	public String getContactname() {
		return this.contactname;
	}

	public void setContactname(String contactname) {
		this.contactname = contactname;
	}

	@Column(name = "planep")
	public Boolean getPlanep() {
		return this.planep;
	}

	public void setPlanep(Boolean planep) {
		this.planep = planep;
	}

	@Column(name = "planec")
	public Boolean getPlanec() {
		return this.planec;
	}

	public void setPlanec(Boolean planec) {
		this.planec = planec;
	}

	@Column(name = "type", nullable = false)
	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	@Column(name = "elevatorquantity")
	public Integer getElevatorquantity() {
		return this.elevatorquantity;
	}

	public void setElevatorquantity(Integer elevatorquantity) {
		this.elevatorquantity = elevatorquantity;
	}

	@Column(name = "motorquantity")
	public Integer getMotorquantity() {
		return this.motorquantity;
	}

	public void setMotorquantity(Integer motorquantity) {
		this.motorquantity = motorquantity;
	}

	@Column(name = "motortraction", length = 10)
	public String getMotortraction() {
		return this.motortraction;
	}

	public void setMotortraction(String motortraction) {
		this.motortraction = motortraction;
	}

	@Column(name = "stopnumber")
	public Integer getStopnumber() {
		return this.stopnumber;
	}

	public void setStopnumber(Integer stopnumber) {
		this.stopnumber = stopnumber;
	}

	@Column(name = "tour")
	public Integer getTour() {
		return this.tour;
	}

	public void setTour(Integer tour) {
		this.tour = tour;
	}

	@Column(name = "ontour")
	public Integer getOntour() {
		return this.ontour;
	}

	public void setOntour(Integer ontour) {
		this.ontour = ontour;
	}

	@Column(name = "widthhole")
	public Integer getWidthhole() {
		return this.widthhole;
	}

	public void setWidthhole(Integer widthhole) {
		this.widthhole = widthhole;
	}

	@Column(name = "fossa")
	public Integer getFossa() {
		return this.fossa;
	}

	public void setFossa(Integer fossa) {
		this.fossa = fossa;
	}

	@Column(name = "bottomhole")
	public Integer getBottomhole() {
		return this.bottomhole;
	}

	public void setBottomhole(Integer bottomhole) {
		this.bottomhole = bottomhole;
	}

	@Column(name = "designspecial")
	public Boolean getDesignspecial() {
		return this.designspecial;
	}

	public void setDesignspecial(Boolean designspecial) {
		this.designspecial = designspecial;
	}

	@Column(name = "designspecialcomment", length = 300)
	public String getDesignspecialcomment() {
		return this.designspecialcomment;
	}

	public void setDesignspecialcomment(String designspecialcomment) {
		this.designspecialcomment = designspecialcomment;
	}

	@Column(name = "doorofnumber")
	public Integer getDoorofnumber() {
		return this.doorofnumber;
	}

	public void setDoorofnumber(Integer doorofnumber) {
		this.doorofnumber = doorofnumber;
	}

	@Column(name = "hallbutton", length = 100)
	public String getHallbutton() {
		return this.hallbutton;
	}

	public void setHallbutton(String hallbutton) {
		this.hallbutton = hallbutton;
	}

	@Column(name = "lightcurtain")
	public Boolean getLightcurtain() {
		return this.lightcurtain;
	}

	public void setLightcurtain(Boolean lightcurtain) {
		this.lightcurtain = lightcurtain;
	}

	@Column(name = "loadlimiter")
	public Boolean getLoadlimiter() {
		return this.loadlimiter;
	}

	public void setLoadlimiter(Boolean loadlimiter) {
		this.loadlimiter = loadlimiter;
	}

	@Column(name = "speechsynthesizer")
	public Boolean getSpeechsynthesizer() {
		return this.speechsynthesizer;
	}

	public void setSpeechsynthesizer(Boolean speechsynthesizer) {
		this.speechsynthesizer = speechsynthesizer;
	}

	@Column(name = "gomsystem")
	public Boolean getGomsystem() {
		return this.gomsystem;
	}

	public void setGomsystem(Boolean gomsystem) {
		this.gomsystem = gomsystem;
	}

	@Column(name = "intercom")
	public Boolean getIntercom() {
		return this.intercom;
	}

	public void setIntercom(Boolean intercom) {
		this.intercom = intercom;
	}

	@Column(name = "phone")
	public Boolean getPhone() {
		return this.phone;
	}

	public void setPhone(Boolean phone) {
		this.phone = phone;
	}

	@Column(name = "accesssytem")
	public Boolean getAccesssytem() {
		return this.accesssytem;
	}

	public void setAccesssytem(Boolean accesssytem) {
		this.accesssytem = accesssytem;
	}

	@Column(name = "firefighterkeychain")
	public Boolean getFirefighterkeychain() {
		return this.firefighterkeychain;
	}

	public void setFirefighterkeychain(Boolean firefighterkeychain) {
		this.firefighterkeychain = firefighterkeychain;
	}

	@Column(name = "comment", length = 300)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "displayplacefloor", length = 50)
	public String getDisplayplacefloor() {
		return this.displayplacefloor;
	}

	public void setDisplayplacefloor(String displayplacefloor) {
		this.displayplacefloor = displayplacefloor;
	}

	@Column(name = "stopsequencecontinuous")
	public Boolean getStopsequencecontinuous() {
		return this.stopsequencecontinuous;
	}

	public void setStopsequencecontinuous(Boolean stopsequencecontinuous) {
		this.stopsequencecontinuous = stopsequencecontinuous;
	}

	@Column(name = "stopsequencecontinuousq", length = 50)
	public String getStopsequencecontinuousq() {
		return this.stopsequencecontinuousq;
	}

	public void setStopsequencecontinuousq(String stopsequencecontinuousq) {
		this.stopsequencecontinuousq = stopsequencecontinuousq;
	}

	@Column(name = "stopsequenceeven")
	public Boolean getStopsequenceeven() {
		return this.stopsequenceeven;
	}

	public void setStopsequenceeven(Boolean stopsequenceeven) {
		this.stopsequenceeven = stopsequenceeven;
	}

	@Column(name = "stopsequenceevenq", length = 50)
	public String getStopsequenceevenq() {
		return this.stopsequenceevenq;
	}

	public void setStopsequenceevenq(String stopsequenceevenq) {
		this.stopsequenceevenq = stopsequenceevenq;
	}

	@Column(name = "stopsequenceodd")
	public Boolean getStopsequenceodd() {
		return this.stopsequenceodd;
	}

	public void setStopsequenceodd(Boolean stopsequenceodd) {
		this.stopsequenceodd = stopsequenceodd;
	}

	@Column(name = "stopsequenceoddq", length = 50)
	public String getStopsequenceoddq() {
		return this.stopsequenceoddq;
	}

	public void setStopsequenceoddq(String stopsequenceoddq) {
		this.stopsequenceoddq = stopsequenceoddq;
	}

	@Column(name = "doorframegray")
	public Boolean getDoorframegray() {
		return this.doorframegray;
	}

	public void setDoorframegray(Boolean doorframegray) {
		this.doorframegray = doorframegray;
	}

	@Column(name = "doorframegraydescrip", length = 50)
	public String getDoorframegraydescrip() {
		return this.doorframegraydescrip;
	}

	public void setDoorframegraydescrip(String doorframegraydescrip) {
		this.doorframegraydescrip = doorframegraydescrip;
	}

	@Column(name = "doorframebrown")
	public Boolean getDoorframebrown() {
		return this.doorframebrown;
	}

	public void setDoorframebrown(Boolean doorframebrown) {
		this.doorframebrown = doorframebrown;
	}

	@Column(name = "doorframebrowndescrip", length = 50)
	public String getDoorframebrowndescrip() {
		return this.doorframebrowndescrip;
	}

	public void setDoorframebrowndescrip(String doorframebrowndescrip) {
		this.doorframebrowndescrip = doorframebrowndescrip;
	}

	@Column(name = "doorframestainless")
	public Boolean getDoorframestainless() {
		return this.doorframestainless;
	}

	public void setDoorframestainless(Boolean doorframestainless) {
		this.doorframestainless = doorframestainless;
	}

	@Column(name = "doorframestainlessdescrip", length = 50)
	public String getDoorframestainlessdescrip() {
		return this.doorframestainlessdescrip;
	}

	public void setDoorframestainlessdescrip(String doorframestainlessdescrip) {
		this.doorframestainlessdescrip = doorframestainlessdescrip;
	}

	@Column(name = "sistelwdisplaypb")
	public Integer getSistelwdisplaypb() {
		return this.sistelwdisplaypb;
	}

	public void setSistelwdisplaypb(Integer sistelwdisplaypb) {
		this.sistelwdisplaypb = sistelwdisplaypb;
	}

	@Column(name = "sistelwdisplayfloor")
	public Integer getSistelwdisplayfloor() {
		return this.sistelwdisplayfloor;
	}

	public void setSistelwdisplayfloor(Integer sistelwdisplayfloor) {
		this.sistelwdisplayfloor = sistelwdisplayfloor;
	}

	@Column(name = "sistelwarrowpb")
	public Integer getSistelwarrowpb() {
		return this.sistelwarrowpb;
	}

	public void setSistelwarrowpb(Integer sistelwarrowpb) {
		this.sistelwarrowpb = sistelwarrowpb;
	}

	@Column(name = "sistelwarrowfloor")
	public Integer getSistelwarrowfloor() {
		return this.sistelwarrowfloor;
	}

	public void setSistelwarrowfloor(Integer sistelwarrowfloor) {
		this.sistelwarrowfloor = sistelwarrowfloor;
	}

	@Column(name = "braile37pb", nullable = false)
	public Integer getBraile37pb() {
		return this.braile37pb;
	}

	public void setBraile37pb(Integer braile37pb) {
		this.braile37pb = braile37pb;
	}

	@Column(name = "braile37floor")
	public Integer getBraile37floor() {
		return this.braile37floor;
	}

	public void setBraile37floor(Integer braile37floor) {
		this.braile37floor = braile37floor;
	}

	@Column(name = "antivandalismpb")
	public Integer getAntivandalismpb() {
		return this.antivandalismpb;
	}

	public void setAntivandalismpb(Integer antivandalismpb) {
		this.antivandalismpb = antivandalismpb;
	}

	@Column(name = "antivandalismfloor", nullable = false)
	public Integer getAntivandalismfloor() {
		return this.antivandalismfloor;
	}

	public void setAntivandalismfloor(Integer antivandalismfloor) {
		this.antivandalismfloor = antivandalismfloor;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
