package database;

// Generated 22-mar-2013 11:18:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessPartner generated by hbm2java
 */
@Entity
@Table(name = "business_partner", catalog = "ascensor_nardi")
public class BusinessPartner implements java.io.Serializable {

	private Integer idBusinessPartner;
	private BasicData basicData;
	private String rif;
	private String name;
	private String address;
	private char status;
	private Set<Budget> budgets = new HashSet<Budget>(0);

	public BusinessPartner() {
	}

	public BusinessPartner(BasicData basicData, String rif, String name,
			char status) {
		this.basicData = basicData;
		this.rif = rif;
		this.name = name;
		this.status = status;
	}

	public BusinessPartner(BasicData basicData, String rif, String name,
			String address, char status, Set<Budget> budgets) {
		this.basicData = basicData;
		this.rif = rif;
		this.name = name;
		this.address = address;
		this.status = status;
		this.budgets = budgets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_business_partner", unique = true, nullable = false)
	public Integer getIdBusinessPartner() {
		return this.idBusinessPartner;
	}

	public void setIdBusinessPartner(Integer idBusinessPartner) {
		this.idBusinessPartner = idBusinessPartner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rif_type", nullable = false)
	public BasicData getBasicData() {
		return this.basicData;
	}

	public void setBasicData(BasicData basicData) {
		this.basicData = basicData;
	}

	@Column(name = "rif", nullable = false, length = 15)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPartner")
	public Set<Budget> getBudgets() {
		return this.budgets;
	}

	public void setBudgets(Set<Budget> budgets) {
		this.budgets = budgets;
	}

}
