package database;

// Generated 24/11/2012 10:42:56 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Databasicmanytomany generated by hbm2java
 */
@Entity
@Table(name = "databasicmanytomany", schema = "public")
public class Databasicmanytomany implements java.io.Serializable {

	private int iddatabasicmanytomany;
	private Budget budget;
	private Basicdata basicdata;
	private String description;

	public Databasicmanytomany() {
	}

	public Databasicmanytomany(int iddatabasicmanytomany, Budget budget,
			Basicdata basicdata) {
		this.iddatabasicmanytomany = iddatabasicmanytomany;
		this.budget = budget;
		this.basicdata = basicdata;
	}

	public Databasicmanytomany(int iddatabasicmanytomany, Budget budget,
			Basicdata basicdata, String description) {
		this.iddatabasicmanytomany = iddatabasicmanytomany;
		this.budget = budget;
		this.basicdata = basicdata;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator="dbmanytomany_seq")
	@SequenceGenerator(name="dbmanytomany_seq", sequenceName="databasicmanytomany_iddatabasicmanytomany_seq")
	@Column(name = "iddatabasicmanytomany", unique = true, nullable = false)
	public int getIddatabasicmanytomany() {
		return this.iddatabasicmanytomany;
	}

	public void setIddatabasicmanytomany(int iddatabasicmanytomany) {
		this.iddatabasicmanytomany = iddatabasicmanytomany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbudget", nullable = false)
	public Budget getBudget() {
		return this.budget;
	}

	public void setBudget(Budget budget) {
		this.budget = budget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Basicdata getBasicdata() {
		return this.basicdata;
	}

	public void setBasicdata(Basicdata basicdata) {
		this.basicdata = basicdata;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
