package database;

// Generated 02/11/2012 09:47:33 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hallbuttontype generated by hbm2java
 */
@Entity
@Table(name = "hallbuttontype", schema = "public")
public class Hallbuttontype implements java.io.Serializable {

	private int idhallbuttontype;
	private Budget budget;
	private int quantitybuttonpb;
	private int quantitybuttonfloor;
	private int totalbuttons;

	public Hallbuttontype() {
	}

	public Hallbuttontype(int idhallbuttontype, Budget budget,
			int quantitybuttonpb, int quantitybuttonfloor, int totalbuttons) {
		this.idhallbuttontype = idhallbuttontype;
		this.budget = budget;
		this.quantitybuttonpb = quantitybuttonpb;
		this.quantitybuttonfloor = quantitybuttonfloor;
		this.totalbuttons = totalbuttons;
	}

	@Id
	@Column(name = "idhallbuttontype", unique = true, nullable = false)
	public int getIdhallbuttontype() {
		return this.idhallbuttontype;
	}

	public void setIdhallbuttontype(int idhallbuttontype) {
		this.idhallbuttontype = idhallbuttontype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbudget", nullable = false)
	public Budget getBudget() {
		return this.budget;
	}

	public void setBudget(Budget budget) {
		this.budget = budget;
	}

	@Column(name = "quantitybuttonpb", nullable = false)
	public int getQuantitybuttonpb() {
		return this.quantitybuttonpb;
	}

	public void setQuantitybuttonpb(int quantitybuttonpb) {
		this.quantitybuttonpb = quantitybuttonpb;
	}

	@Column(name = "quantitybuttonfloor", nullable = false)
	public int getQuantitybuttonfloor() {
		return this.quantitybuttonfloor;
	}

	public void setQuantitybuttonfloor(int quantitybuttonfloor) {
		this.quantitybuttonfloor = quantitybuttonfloor;
	}

	@Column(name = "totalbuttons", nullable = false)
	public int getTotalbuttons() {
		return this.totalbuttons;
	}

	public void setTotalbuttons(int totalbuttons) {
		this.totalbuttons = totalbuttons;
	}

}
