package database;

// Generated 22-mar-2013 11:18:27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecurityUser generated by hbm2java
 */
@Entity
@Table(name = "security_user", catalog = "ascensor_nardi")
public class SecurityUser implements java.io.Serializable {

	private Integer idSecurityUser;
	private String name;
	private String email;
	private String password;
	private String phone;
	private char status;
	private Set<Budget> budgets = new HashSet<Budget>(0);
	private Set<SecurityGroup> securityGroups = new HashSet<SecurityGroup>(0);

	public SecurityUser() {
	}

	public SecurityUser(String name, String email, String password,
			String phone, char status) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.status = status;
	}

	public SecurityUser(String name, String email, String password,
			String phone, char status, Set<Budget> budgets,
			Set<SecurityGroup> securityGroups) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.status = status;
		this.budgets = budgets;
		this.securityGroups = securityGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_security_user", unique = true, nullable = false)
	public Integer getIdSecurityUser() {
		return this.idSecurityUser;
	}

	public void setIdSecurityUser(Integer idSecurityUser) {
		this.idSecurityUser = idSecurityUser;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "securityUser")
	public Set<Budget> getBudgets() {
		return this.budgets;
	}

	public void setBudgets(Set<Budget> budgets) {
		this.budgets = budgets;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "group_user", catalog = "ascensor_nardi", joinColumns = { @JoinColumn(name = "id_security_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_security_group", nullable = false, updatable = false) })
	public Set<SecurityGroup> getSecurityGroups() {
		return this.securityGroups;
	}

	public void setSecurityGroups(Set<SecurityGroup> securityGroups) {
		this.securityGroups = securityGroups;
	}

}
