package model.database;

// Generated 20-jun-2014 9:51:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BudgetDetailOtherCostumers generated by hbm2java
 */
@Entity
@Table(name = "budget_detail_other_costumers", schema = "public")
public class BudgetDetailOtherCostumers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5434108247244838740L;
	private int idBudgetDetail;
	private String code;
	private String name;
	private Float cost;
	private Float price;
	private String number;
	private Integer cantidad;
	private Character estatus;

	public BudgetDetailOtherCostumers() {
	}

	public BudgetDetailOtherCostumers(int idBudgetDetail) {
		this.idBudgetDetail = idBudgetDetail;
	}

	public BudgetDetailOtherCostumers(int idBudgetDetail, String code, String name, Float cost, Float price, String number, Integer cantidad, Character estatus) {
		this.idBudgetDetail = idBudgetDetail;
		this.code = code;
		this.name = name;
		this.cost = cost;
		this.price = price;
		this.number = number;
		this.cantidad = cantidad;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "budget_detail_other_costumers_seq")
	@SequenceGenerator(name = "budget_detail_other_costumers_seq", sequenceName = "budget_detail_other_costumers_id_budget_detail_seq")
	@Column(name = "id_budget_detail", unique = true, nullable = false)
	public int getIdBudgetDetail() {
		return this.idBudgetDetail;
	}

	public void setIdBudgetDetail(int idBudgetDetail) {
		this.idBudgetDetail = idBudgetDetail;
	}

	@Column(name = "code", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cost", precision = 8, scale = 8)
	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	@Column(name = "price", precision = 8, scale = 8)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "number", length = 15)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "estatus", length = 1)
	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

}
