package model.database;

// Generated 20-jun-2014 9:51:18 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudgetOtherCostumers generated by hbm2java
 */
@Entity
@Table(name = "budget_other_costumers", schema = "public")
public class BudgetOtherCostumers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8291145968155531847L;
	private int idBudgetOtherCostumers;
	private BusinessPartner businessPartner;
	private SecurityUser securityUser;
	private String number;
	private char rifType;
	private String rifPartner;
	private String partnerName;
	private String seller;
	private String constructionAddress;
	private String constructionCity;
	private String contactPhone;
	private String email;
	private String contactName;
	private char status;
	private Date date;

	public BudgetOtherCostumers() {
	}

	public BudgetOtherCostumers(int idBudgetOtherCostumers, BusinessPartner businessPartner, SecurityUser securityUser, String number, char rifType, String rifPartner, String partnerName, String seller, String constructionAddress, String constructionCity, String contactPhone, String contactName, char status) {
		this.idBudgetOtherCostumers = idBudgetOtherCostumers;
		this.businessPartner = businessPartner;
		this.securityUser = securityUser;
		this.number = number;
		this.rifType = rifType;
		this.rifPartner = rifPartner;
		this.partnerName = partnerName;
		this.seller = seller;
		this.constructionAddress = constructionAddress;
		this.constructionCity = constructionCity;
		this.contactPhone = contactPhone;
		this.contactName = contactName;
		this.status = status;
	}

	public BudgetOtherCostumers(int idBudgetOtherCostumers, BusinessPartner businessPartner, SecurityUser securityUser, String number, char rifType, String rifPartner, String partnerName, String seller, String constructionAddress, String constructionCity, String contactPhone, String email, String contactName, char status, Date date) {
		this.idBudgetOtherCostumers = idBudgetOtherCostumers;
		this.businessPartner = businessPartner;
		this.securityUser = securityUser;
		this.number = number;
		this.rifType = rifType;
		this.rifPartner = rifPartner;
		this.partnerName = partnerName;
		this.seller = seller;
		this.constructionAddress = constructionAddress;
		this.constructionCity = constructionCity;
		this.contactPhone = contactPhone;
		this.email = email;
		this.contactName = contactName;
		this.status = status;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "budget_other_costumers_seq")
	@SequenceGenerator(name = "budget_other_costumers_seq", sequenceName = "budget_other_costumers_id_budget_other_costumers_seq")
	@Column(name = "id_budget_other_costumers", unique = true, nullable = false)
	public int getIdBudgetOtherCostumers() {
		return this.idBudgetOtherCostumers;
	}

	public void setIdBudgetOtherCostumers(int idBudgetOtherCostumers) {
		this.idBudgetOtherCostumers = idBudgetOtherCostumers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_business_partner", nullable = false)
	public BusinessPartner getBusinessPartner() {
		return this.businessPartner;
	}

	public void setBusinessPartner(BusinessPartner businessPartner) {
		this.businessPartner = businessPartner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_security_user", nullable = false)
	public SecurityUser getSecurityUser() {
		return this.securityUser;
	}

	public void setSecurityUser(SecurityUser securityUser) {
		this.securityUser = securityUser;
	}

	@Column(name = "number", nullable = false, length = 15)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "rif_type", nullable = false, length = 1)
	public char getRifType() {
		return this.rifType;
	}

	public void setRifType(char rifType) {
		this.rifType = rifType;
	}

	@Column(name = "rif_partner", nullable = false, length = 100)
	public String getRifPartner() {
		return this.rifPartner;
	}

	public void setRifPartner(String rifPartner) {
		this.rifPartner = rifPartner;
	}

	@Column(name = "partner_name", nullable = false, length = 100)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "seller", nullable = false, length = 100)
	public String getSeller() {
		return this.seller;
	}

	public void setSeller(String seller) {
		this.seller = seller;
	}

	@Column(name = "construction_address", nullable = false, length = 200)
	public String getConstructionAddress() {
		return this.constructionAddress;
	}

	public void setConstructionAddress(String constructionAddress) {
		this.constructionAddress = constructionAddress;
	}

	@Column(name = "construction_city", nullable = false, length = 100)
	public String getConstructionCity() {
		return this.constructionCity;
	}

	public void setConstructionCity(String constructionCity) {
		this.constructionCity = constructionCity;
	}

	@Column(name = "contact_phone", nullable = false, length = 30)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_name", nullable = false, length = 100)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
