package model.database;

// Generated 25-mar-2014 16:49:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WarrantyNotes generated by hbm2java
 */
@Entity
@Table(name = "warranty_notes", schema = "public")
public class WarrantyNotes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5650798555961914105L;

	private int idWarranty;
	private String name;
	private String field;
	private char status;

	public WarrantyNotes() {
	}


	public WarrantyNotes(int idWarranty, char status) {
		this.idWarranty = idWarranty;
		this.status = status;
	}

	public WarrantyNotes(int idWarranty, String name, String field, char status) {
		this.idWarranty = idWarranty;
		this.name = name;
		this.field = field;
		this.status = status;
	}

	@Id
	@Column(name = "id_warranty", unique = true, nullable = false)
	public int getIdWarranty() {
		return this.idWarranty;
	}

	public void setIdWarranty(int idWarranty) {
		this.idWarranty = idWarranty;
	}

	@Column(name = "name", length = 1500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "field", length = 120)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
